# NumPy Fundamentals

## Intro To Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

If you don't have NumPy installed, `pip install numpy`

In [4]:
import numpy as np

### Creating NumPy arrays

In [5]:
# convert python list to numpy array
np1 = np.array([1,2,3,4,5]) # 1,2,3,4,5

# np.arange(start, stop, step)
np2 = np.arange(5) # 0,1,2,3,4
np3 = np.arange(5, 10) # 5,6,7,8,9
np4 = np.arange(5, 10, 2) # 5,7,9

# np.linspace(start, stop, num)
np5 = np.linspace(0, 10, 5) # 0,2.5,5,7.5,10

# np.zero and np.ones
np6 = np.zeros(5) # 0,0,0,0,0
np7 = np.ones(5) # 1,1,1,1,1

# np.full(shape, value)
np8 = np.full(5, 5) # 5,5,5,5,5
np9 = np.full((2,2), 5) # [[5,5],[5,5]]

In [6]:
# np.eye
np10 = np.eye(5) # 5x5 identity matrix

# np.random.rand
np11 = np.random.rand(5) # 5 random numbers between 0 and 1

# np.random.randint
np12 = np.random.randint(1, 10, 5) # 5 random numbers between 1 and 10

# specify data type
Z = np.array([[1,2],[3,4]], dtype=np.float64)

**seeing the shape**

In [7]:
print(np9)

print(f"shape: {np9.shape}") # prints the shape of the array
print(f"dimensions: {np9.ndim}") # prints the number of dimensions of the array

[[5 5]
 [5 5]]
shape: (2, 2)
dimensions: 2


**size and byte**

In [8]:
Z = np.array([1,2,3])

print(f"size: {Z.size}") # prints the size of the array
print(f"size of each item: {Z.itemsize}")  # prints the size of the elements in the array
print(f"total size of array in bytes: {Z.nbytes}") # prints the total size of the array in bytes

size: 3
size of each item: 8
total size of array in bytes: 24


### Slicing and indexing

**SLICING**

In [9]:
np1 = np.arange(1, 10) # 1,2,3,4,5,6,7,8,9

print(np1[1:5]) # 2,3,4,5
print(np1[:5]) # 1,2,3,4,5

print(np1[::2]) # 1,3,5,7,9
print(np1[::]) # 1,2,3,4,5,6,7,8,9
print(np1[::-1]) # 9,8,7,6,5,4,3,2,1
print(np1[1:-1:-1]) # empty array. If the step is negative, the start and stop should be reversed.

[2 3 4 5]
[1 2 3 4 5]
[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[]


what if the array is not 1d?

In [10]:
np2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np2[::-1])

print(np2[::-1, ::-1])
# we can observe that slicing can be specified for each dimension
# the first position is the 'outermost' dimension, and the last position is the 'innermost' dimension

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


**INDEXING**

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [11]:
Z = np.array([1,2,3])
# Z[2] is a "view" of Z, and not a copy. So modifying Z[2] will modify Z as well
Z[2] = 100
print(Z)

[  1   2 100]


generally, accessing in single-step `arr[x,y]` is more efficient than doing `arr[x][y]`

In [12]:
np3 = np.array([[1,2,3], [4,5,6], [7,8,9]])


print(np3[1,2])
# This is a single-step operation where NumPy directly accesses the specified element using multidimensional indexing

print(np3[1][2]) # 6
# This is a two-step operation where NumPy first accesses the first dimension and then the second dimension

6
6


You can also integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [13]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [14]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [15]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer Array Indexing (Fancy Indexing)**

In [16]:
np1 = np.arange(1, 10) # 1,2,3,4,5,6,7,8,9
indices = np.array([1, 3, 4])
print(np1[indices])

# or you can just use list directly
print(np1[[1, 3, 4]])

[2 4 5]
[2 4 5]


In [17]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [18]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print("\n", a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [ 1  6  7 11]


In [19]:
# Mutate first element from each row
a[np.arange(4), 0] += 10
print(a)

[[11  2  3]
 [14  5  6]
 [17  8  9]
 [20 11 12]]


**boolean indexing**

In [20]:

a = np.array([1, 2, 3, 4, 5])
# Create a boolean array where True represents values greater than 2
bool_idx = a > 2

print(bool_idx)
# Output: [False False  True  True  True]

# Use this boolean array to index the original array
print(a[bool_idx])
# Output: [3 4 5]

# Or directly
print(a[a > 2])
# Output: [3 4 5]

[False False  True  True  True]
[3 4 5]
[3 4 5]


**[EXTRA]** There are other advanced slicing/indexing techniques such as:
- Ellipsis and np.newaxis  

### NumPy Universal Functions

**Universal Functions** are functions that operate element-wise on an ndarray  

Check [NumPy ufunc documentation](https://numpy.org/doc/stable/reference/ufuncs.html) for more!

Arithmetic Operations

- **np.add(x, y):** Adds corresponding elements in arrays x and y.
- **np.subtract(x, y):** Subtracts elements of y from x.
- **np.multiply(x, y):** Multiplies elements of x by elements of y.
- **np.divide(x, y):** Divides elements of x by elements of y.
- **np.sqrt(x):** Returns the non-negative square-root of an array, element-wise.

Matrix-wise
- **np.dot():** dot product 
- **np.matmul(x, y):** Matrix Multiplication (Linear algebra)
- **np.transpose(x):** transposition of matrix x,y --> y,x (or just `x.T` for transposing attribute) 

Trigonometric Functions

- **np.sin(x):** Trigonometric sine, element-wise.
- **np.cos(x):** Trigonometric cosine, element-wise.
- **np.tan(x):** Trigonometric tangent, element-wise.

Exponential and Logarithmic Functions

- **np.exp(x):** Calculates the exponential of all elements in the input array.
- **np.log(x):** Natural logarithm, element-wise.
- **np.log10(x):** Base-10 logarithm of x.

Others

- **np.absolute(x):** Takes the absolute value element-wise
- **np.sign(x):** Returns -1, 0, 1 based on the sign of elements


Aggregation Functions

- **np.sum(x):** Sum of array elements over a given axis.
- **np.mean(x):** Compute the arithmetic mean along the specified axis.
- **np.std(x):** Compute the standard deviation along the specified axis.
- **np.min(x), np.max(x):** Minimum and maximum of an array or minimum along an axis.


Comparison Functions

- **np.greater(x, y), np.less(x, y):** Element-wise comparison of array elements.
- **np.equal(x, y):** Checks whether each element of x is exactly equal to the corresponding element of y.


Logical Operations

- **np.logical_and(x, y):** Compute the truth value of x AND y element-wise.
- **np.logical_or(x, y):** Compute the truth value of x OR y element-wise.
- **np.logical_not(x):** Compute the truth value of NOT x element-wise.

In [21]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

# finding the maximum value in the entire array
print(A.max())
print(A.mean())

9
5.0


Use `axis` parameter to perform operations on specific dimension  

axis=0 refers to the outermost dimension, which is the first dimension of the array.   
For a 2D array, this would be the rows, and for a 3D array, it would be the layers of 2D arrays stacked on top of each other.

In [22]:
# finding the maximum values in each 0 axis, i.e., outermost dimension (column)
print(A.max(axis=0)) # [7 8 9]

# finding the maximum values in each 1 axis, i.e., inner dimension (row)
print(A.max(axis=1)) # [3 6 9]

[7 8 9]
[3 6 9]


In [23]:
B = np.random.randint(1, 10, 12).reshape(2,2,3)
print(B, "\n")

# finding the maximum values in each 0 axis (in 3D, this is the 'depth' axis)
print("max values in depth axis (2D arrays stacked on top of each other):")
print(B.max(axis=0))

[[[7 4 1]
  [1 1 5]]

 [[3 8 1]
  [6 2 5]]] 

max values in depth axis (2D arrays stacked on top of each other):
[[7 8 1]
 [6 2 5]]


### Copy vs View

`np2 = np1` in NumPy creates a reference to the same array object as np1, meaning any changes made to np2 will also reflect in np1 and vice versa.   

`np2 = np1.view()` creates a new view object of np1, which shares the same data but allows for changes in shape or strides without altering the original data. Modifications to the data through np2 will affect np1, but changes to the shape of np2 will not affect np1.

`np2 = np1.copy()` creates a deepcopy of np1

### Reshaping

In [24]:
# 1D array
np1 = np.arange(1, 13) # 1,2,3,4,5,6,7,8,9,10,11,12
print(f"Original 1D array: \n {np1} \n")

print(f"shape is {np1.shape}")

Original 1D array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 

shape is (12,)


In [25]:
# reshaping to 2D array
np2 = np1.reshape(3, 4)
print(f"Reshaped 2D array: \n {np2} \n")

# reshaping to 3D array
np3 = np1.reshape(2, 2, 3)
print(f"Reshaped 3D array: \n {np3}")

Reshaped 2D array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Reshaped 3D array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


you can use `-1` to automatically reshape

In [26]:
np2 = np1.reshape(3, -1)
np3 = np1.reshape(-1, 3, 2)
# -1 means that the value is inferred from the length of the array and the remaining dimensions

np1 = np3.reshape(-1)
# this flattens np3 into a 1D array

### Iterating through ndarrays

you can iterate manually through nested loops:

In [27]:
np1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
for row in np1:
    print(row)
    for element in row:
        print(element)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


`np.nditer()` is more convenient to iterate through every element

In [28]:
for x in np.nditer(np1):
    print(x)

1
2
3
4
5
6
7
8
9


`np.ndenumerate` acts like enumerate(). It returns a tuple with index and element at that index

In [29]:
for (index, x) in np.ndenumerate(np1):
    print(index, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


## Additional Information

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [30]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are a couple of visual examples involving broadcasting. 


![](http://jalammar.github.io/images/numpy/numpy-array-broadcast.png)

Note the application of rule #2 - these arrays are compatible in each dimension if they have either the same size in that dimension, or if one array has size 1 in that dimension.

![](http://jalammar.github.io/images/numpy/numpy-matrix-broadcast.png)

And here are some more practical applications:



In [31]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [32]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [33]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [34]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [35]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.