# NumPy Fundamentals

## Intro To Numpy

If you don't have NumPy installed, `pip install numpy`

In [3]:
import numpy as np

### Creating NumPy arrays

In [48]:
# convert python list to numpy array
np1 = np.array([1,2,3,4,5]) # 1,2,3,4,5

# np.arange(start, stop, step)
np2 = np.arange(5) # 0,1,2,3,4
np3 = np.arange(5, 10) # 5,6,7,8,9
np4 = np.arange(5, 10, 2) # 5,7,9

# np.linspace(start, stop, num)
np5 = np.linspace(0, 10, 5) # 0,2.5,5,7.5,10

# np.zero and np.ones
np6 = np.zeros(5) # 0,0,0,0,0
np7 = np.ones(5) # 1,1,1,1,1

# np.full(shape, value)
np8 = np.full(5, 5) # 5,5,5,5,5
np9 = np.full((2,2), 5) # [[5,5],[5,5]]

# np.eye
np10 = np.eye(5) # 5x5 identity matrix

# np.random.rand
np11 = np.random.rand(5) # 5 random numbers between 0 and 1

# np.random.randint
np12 = np.random.randint(1, 10, 5) # 5 random numbers between 1 and 10


**seeing the shape**

In [49]:
print(np9)

print(f"shape: {np9.shape}") # prints the shape of the array
print(f"dimensions: {np9.ndim}") # prints the number of dimensions of the array

[[5 5]
 [5 5]]
shape: (2, 2)
dimensions: 2


**size and byte**

In [46]:
Z = np.array([1,2,3])

print(f"size: {Z.size}") # prints the size of the array
print(f"size of each item: {Z.itemsize}")  # prints the size of the elements in the array
print(f"total size of array in bytes: {Z.nbytes}") # prints the total size of the array in bytes

size: 3
size of each item: 8
total size of array in bytes: 24


### Slicing and indexing

**SLICING**

In [ ]:
np1 = np.arange(1, 10) # 1,2,3,4,5,6,7,8,9

print(np1[1:5]) # 2,3,4,5
print(np1[:5]) # 1,2,3,4,5

print(np1[::2]) # 1,3,5,7,9
print(np1[::]) # 1,2,3,4,5,6,7,8,9
print(np1[::-1]) # 9,8,7,6,5,4,3,2,1
print(np1[1:-1:-1]) # empty array. If the step is negative, the start and stop should be reversed.

what if the array is not 1d?

In [ ]:
np2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np2[::-1])
print(np2[::-1, ::-1])
# we can observe that slicing needs to be specified for each dimension
# the first position is the 'outermost' dimension, and the last position is the 'innermost' dimension

**INDEXING**

generally, accessing in single-step `arr[x,y]` is more efficient than doing `arr[x][y]`

In [ ]:
np3 = np.array([[1,2,3], [4,5,6], [7,8,9]])


print(np3[1,2])
# This is a single-step operation where NumPy directly accesses the specified element using multidimensional indexing

print(np3[1][2]) # 6
# This is a two-step operation where NumPy first accesses the first dimension and then the second dimension

**Integer Array Indexing (Fancy Indexing)**

In [43]:
np1 = np.arange(1, 10) # 1,2,3,4,5,6,7,8,9
indices = np.array([1, 3, 4])
print(np1[indices])

# or you can just use list directly
print(np1[[1, 3, 4]])

[2 4 5]
[2 4 5]


**boolean indexing**

In [32]:

a = np.array([1, 2, 3, 4, 5])
# Create a boolean array where True represents values greater than 2
bool_idx = a > 2

print(bool_idx)
# Output: [False False  True  True  True]

# Use this boolean array to index the original array
print(a[bool_idx])
# Output: [3 4 5]

# Or directly
print(a[a > 2])
# Output: [3 4 5]

[False False  True  True  True]
[3 4 5]
[3 4 5]


**[EXTRA]** There are other advanced slicing/indexing techniques such as:
- Ellipsis and np.newaxis  

### NumPy Universal Functions

**Universal Functions** are functions that operate element-wise on an ndarray  

Check [NumPy ufunc documentation](https://numpy.org/doc/stable/reference/ufuncs.html) for more!

Arithmetic Operations

- **np.add(x, y):** Adds corresponding elements in arrays x and y.
- **np.subtract(x, y):** Subtracts elements of y from x.
- **np.multiply(x, y):** Multiplies elements of x by elements of y.
- **np.divide(x, y):** Divides elements of x by elements of y.
- **np.sqrt(x):** Returns the non-negative square-root of an array, element-wise.
- **np.matmul(x, y):** Matrix Multiplication (Linear algebra)

Trigonometric Functions

- **np.sin(x):** Trigonometric sine, element-wise.
- **np.cos(x):** Trigonometric cosine, element-wise.
- **np.tan(x):** Trigonometric tangent, element-wise.

Exponential and Logarithmic Functions

- **np.exp(x):** Calculates the exponential of all elements in the input array.
- **np.log(x):** Natural logarithm, element-wise.
- **np.log10(x):** Base-10 logarithm of x.

Others

- **np.absolute(x):** Takes the absolute value element-wise
- **np.sign(x):** Returns -1, 0, 1 based on the sign of elements


Aggregation Functions

- **np.sum(x):** Sum of array elements over a given axis.
- **np.mean(x):** Compute the arithmetic mean along the specified axis.
- **np.std(x):** Compute the standard deviation along the specified axis.
- **np.min(x), np.max(x):** Minimum and maximum of an array or minimum along an axis.


Comparison Functions

- **np.greater(x, y), np.less(x, y):** Element-wise comparison of array elements.
- **np.equal(x, y):** Checks whether each element of x is exactly equal to the corresponding element of y.


Logical Operations

- **np.logical_and(x, y):** Compute the truth value of x AND y element-wise.
- **np.logical_or(x, y):** Compute the truth value of x OR y element-wise.
- **np.logical_not(x):** Compute the truth value of NOT x element-wise.

In [26]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

# finding the maximum value in the entire array
print(A.max())
print(A.mean())

9
5.0


Use `axis` parameter to perform operations on specific dimension  

axis=0 refers to the outermost dimension, which is the first dimension of the array.   
For a 2D array, this would be the rows, and for a 3D array, it would be the layers of 2D arrays stacked on top of each other.

In [40]:
# finding the maximum values in each 0 axis, i.e., outermost dimension (column)
print(A.max(axis=0)) # [7 8 9]

# finding the maximum values in each 1 axis, i.e., inner dimension (row)
print(A.max(axis=1)) # [3 6 9]

[7 8 9]
[3 6 9]


In [ ]:
B = np.random.randint(1, 10, 12).reshape(2,2,3)
print(B, "\n")

# finding the maximum values in each 0 axis (in 3D, this is the 'depth' axis)
print("max values in depth axis (2D arrays stacked on top of each other):")
print(B.max(axis=0))

### Copy vs View

`np2 = np1` in NumPy creates a reference to the same array object as np1, meaning any changes made to np2 will also reflect in np1 and vice versa.   

`np2 = np1.view()` creates a new view object of np1, which shares the same data but allows for changes in shape or strides without altering the original data. Modifications to the data through np2 will affect np1, but changes to the shape of np2 will not affect np1.

`np2 = np1.copy()` creates a deepcopy of np1

### Reshaping

In [11]:
# 1D array
np1 = np.arange(1, 13) # 1,2,3,4,5,6,7,8,9,10,11,12
print(f"Original 1D array: \n {np1} \n")

print(f"shape is {np1.shape}")

Original 1D array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 

shape is (12,)


In [ ]:
# reshaping to 2D array
np2 = np1.reshape(3, 4)
print(f"Reshaped 2D array: \n {np2} \n")

# reshaping to 3D array
np3 = np1.reshape(2, 2, 3)
print(f"Reshaped 3D array: \n {np3}")

you can use `-1` to automatically reshape

In [17]:
np2 = np1.reshape(3, -1)
np3 = np1.reshape(-1, 3, 2)
# -1 means that the value is inferred from the length of the array and the remaining dimensions

np1 = np3.reshape(-1)
# this flattens np3 into a 1D array

### Iterating through ndarrays

you can iterate manually through nested loops:

In [ ]:
np1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
for row in np1:
    print(row)
    for element in row:
        print(element)

`np.nditer()` is more convenient to iterate through every element

In [ ]:
for x in np.nditer(np1):
    print(x)

`np.ndenumerate` acts like enumerate(). It returns a tuple with index and element at that index

In [ ]:
for (index, x) in np.ndenumerate(np1):
    print(index, x)

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package. By convention, we import it using the alias `np`.

In [ ]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can create a `numpy` array by passing a Python list to ` np.array()`. 

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array

This creates the array we can see on the right here:

![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [ ]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


To create a `numpy` array with more dimensions, we can pass nested lists, like this:

![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [ ]:
b = np.array([[1,2],[3,4]])   # Create a rank 2 array
print(b)

[[1 2]
 [3 4]]


In [ ]:
print(b.shape)

(2, 2)


There are often cases when we want numpy to initialize the values of the array for us. numpy provides methods like `ones()`, `zeros()`, and `random.random()` for these cases. We just pass them the number of elements we want it to generate:

![](http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)


We can also use these methods to produce multi-dimensional arrays, as long as we pass them a tuple describing the dimensions of the matrix we want to create:

![](http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)



In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.75164948 0.84834148]
 [0.23587529 0.93488906]]


### Array indexing

Numpy offers several ways to index into arrays.

We can index and slice numpy arrays in all the ways we can slice Python lists:

![](http://jalammar.github.io/images/numpy/numpy-array-slice.png)

And you can index and slice numpy arrays in multiple dimensions. If slicing an array with more than one dimension, you should specify a slice for each dimension:

![](http://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module.



For example, you can perform an elementwise sum on two arrays using either the + operator or the `add()` function.

![](http://jalammar.github.io/images/numpy/numpy-arrays-adding-1.png)


![](http://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png)

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


And this works for other operations as well, not only addition:

![](http://jalammar.github.io/images/numpy/numpy-array-subtract-multiply-divide.png)

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot()` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot()` is available both as a function in the numpy module and as an instance method of array objects:

![](http://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays, such as `min()`, `max()`, `sum()`, and others:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(np.max(x))  # Compute sum of all elements; prints "21"
print(np.min(x))  # Compute sum of all elements; prints "21"
print(np.sum(x))  # Compute sum of all elements; prints "21"

6
1
21


Not only can we aggregate all the values in a matrix using these functions, but we can also aggregate across the rows or columns by using the `axis` parameter:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

In [ ]:
x = np.array([[1, 2], [5, 3], [4, 6]])

print(np.max(x, axis=0))  # Compute max of each column; prints "[5 6]"
print(np.max(x, axis=1))  # Compute max of each row; prints "[2 5 6]"

[5 6]
[2 5 6]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object.

![](http://jalammar.github.io/images/numpy/numpy-transpose.png)

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]
 [5 6]]
transpose
 [[1 3 5]
 [2 4 6]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In more advanced use case, you may find yourself needing to change the dimensions of a certain matrix. This is often the case in machine learning applications where a certain model expects a certain shape for the inputs that is different from your dataset. numpy's `reshape()` method is useful in these cases. 

![](http://jalammar.github.io/images/numpy/numpy-reshape.png)


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.


For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.zeros_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are a couple of visual examples involving broadcasting. 


![](http://jalammar.github.io/images/numpy/numpy-array-broadcast.png)

Note the application of rule #2 - these arrays are compatible in each dimension if they have either the same size in that dimension, or if one array has size 1 in that dimension.

![](http://jalammar.github.io/images/numpy/numpy-matrix-broadcast.png)

And here are some more practical applications:



In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.