# NumPy Fundamentals

## Intro To Numpy

If you don't have NumPy installed, `pip install numpy`

In [3]:
import numpy as np

### Creating NumPy arrays

In [48]:
# convert python list to numpy array
np1 = np.array([1,2,3,4,5]) # 1,2,3,4,5

# np.arange(start, stop, step)
np2 = np.arange(5) # 0,1,2,3,4
np3 = np.arange(5, 10) # 5,6,7,8,9
np4 = np.arange(5, 10, 2) # 5,7,9

# np.linspace(start, stop, num)
np5 = np.linspace(0, 10, 5) # 0,2.5,5,7.5,10

# np.zero and np.ones
np6 = np.zeros(5) # 0,0,0,0,0
np7 = np.ones(5) # 1,1,1,1,1

# np.full(shape, value)
np8 = np.full(5, 5) # 5,5,5,5,5
np9 = np.full((2,2), 5) # [[5,5],[5,5]]

# np.eye
np10 = np.eye(5) # 5x5 identity matrix

# np.random.rand
np11 = np.random.rand(5) # 5 random numbers between 0 and 1

# np.random.randint
np12 = np.random.randint(1, 10, 5) # 5 random numbers between 1 and 10


**seeing the shape**

In [49]:
print(np9)

print(f"shape: {np9.shape}") # prints the shape of the array
print(f"dimensions: {np9.ndim}") # prints the number of dimensions of the array

[[5 5]
 [5 5]]
shape: (2, 2)
dimensions: 2


**size and byte**

In [46]:
Z = np.array([1,2,3])

print(f"size: {Z.size}") # prints the size of the array
print(f"size of each item: {Z.itemsize}")  # prints the size of the elements in the array
print(f"total size of array in bytes: {Z.nbytes}") # prints the total size of the array in bytes

size: 3
size of each item: 8
total size of array in bytes: 24


### Slicing and indexing

**SLICING**

In [ ]:
np1 = np.arange(1, 10) # 1,2,3,4,5,6,7,8,9

print(np1[1:5]) # 2,3,4,5
print(np1[:5]) # 1,2,3,4,5

print(np1[::2]) # 1,3,5,7,9
print(np1[::]) # 1,2,3,4,5,6,7,8,9
print(np1[::-1]) # 9,8,7,6,5,4,3,2,1
print(np1[1:-1:-1]) # empty array. If the step is negative, the start and stop should be reversed.

what if the array is not 1d?

In [ ]:
np2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np2[::-1])
print(np2[::-1, ::-1])
# we can observe that slicing needs to be specified for each dimension
# the first position is the 'outermost' dimension, and the last position is the 'innermost' dimension

**INDEXING**

generally, accessing in single-step `arr[x,y]` is more efficient than doing `arr[x][y]`

In [ ]:
np3 = np.array([[1,2,3], [4,5,6], [7,8,9]])


print(np3[1,2])
# This is a single-step operation where NumPy directly accesses the specified element using multidimensional indexing

print(np3[1][2]) # 6
# This is a two-step operation where NumPy first accesses the first dimension and then the second dimension

**Integer Array Indexing**

In [43]:
np1 = np.arange(1, 10) # 1,2,3,4,5,6,7,8,9
indices = np.array([1, 3, 4])
print(np1[indices])

# or you can just use list directly
print(np1[[1, 3, 4]])

[2 4 5]
[2 4 5]


**[EXTRA] boolean indexing**

In [32]:

a = np.array([1, 2, 3, 4, 5])
# Create a boolean array where True represents values greater than 2
bool_idx = a > 2

print(bool_idx)
# Output: [False False  True  True  True]

# Use this boolean array to index the original array
print(a[bool_idx])
# Output: [3 4 5]

# Or directly
print(a[a > 2])
# Output: [3 4 5]

[False False  True  True  True]
[3 4 5]
[3 4 5]


**[EXTRA]** There are more advanced slicing/indexing techniques such as:   
- Fancy indexing  
- Ellipsis and np.newaxis  


### NumPy Universal Functions

**Universal Functions** are functions that operate element-wise on an ndarray  

Check [NumPy ufunc documentation](https://numpy.org/doc/stable/reference/ufuncs.html) for more!

Arithmetic Operations

- **np.add(x, y):** Adds corresponding elements in arrays x and y.
- **np.subtract(x, y):** Subtracts elements of y from x.
- **np.multiply(x, y):** Multiplies elements of x by elements of y.
- **np.divide(x, y):** Divides elements of x by elements of y.
- **np.sqrt(x):** Returns the non-negative square-root of an array, element-wise.
- **np.matmul(x, y):** Matrix Multiplication (Linear algebra)

Trigonometric Functions

- **np.sin(x):** Trigonometric sine, element-wise.
- **np.cos(x):** Trigonometric cosine, element-wise.
- **np.tan(x):** Trigonometric tangent, element-wise.

Exponential and Logarithmic Functions

- **np.exp(x):** Calculates the exponential of all elements in the input array.
- **np.log(x):** Natural logarithm, element-wise.
- **np.log10(x):** Base-10 logarithm of x.

Others

- **np.absolute(x):** Takes the absolute value element-wise
- **np.sign(x):** Returns -1, 0, 1 based on the sign of elements


Aggregation Functions

- **np.sum(x):** Sum of array elements over a given axis.
- **np.mean(x):** Compute the arithmetic mean along the specified axis.
- **np.std(x):** Compute the standard deviation along the specified axis.
- **np.min(x), np.max(x):** Minimum and maximum of an array or minimum along an axis.


Comparison Functions

- **np.greater(x, y), np.less(x, y):** Element-wise comparison of array elements.
- **np.equal(x, y):** Checks whether each element of x is exactly equal to the corresponding element of y.


Logical Operations

- **np.logical_and(x, y):** Compute the truth value of x AND y element-wise.
- **np.logical_or(x, y):** Compute the truth value of x OR y element-wise.
- **np.logical_not(x):** Compute the truth value of NOT x element-wise.

In [26]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

# finding the maximum value in the entire array
print(A.max())
print(A.mean())

9
5.0


Use `axis` parameter to perform operations on specific dimension  

axis=0 refers to the outermost dimension, which is the first dimension of the array.   
For a 2D array, this would be the rows, and for a 3D array, it would be the layers of 2D arrays stacked on top of each other.

In [40]:
# finding the maximum values in each 0 axis, i.e., outermost dimension (column)
print(A.max(axis=0)) # [7 8 9]

# finding the maximum values in each 1 axis, i.e., inner dimension (row)
print(A.max(axis=1)) # [3 6 9]

[7 8 9]
[3 6 9]


In [ ]:
B = np.random.randint(1, 10, 12).reshape(2,2,3)
print(B, "\n")

# finding the maximum values in each 0 axis (in 3D, this is the 'depth' axis)
print("max values in depth axis (2D arrays stacked on top of each other):")
print(B.max(axis=0))

### Copy vs View

`np2 = np1` in NumPy creates a reference to the same array object as np1, meaning any changes made to np2 will also reflect in np1 and vice versa.   

`np2 = np1.view()` creates a new view object of np1, which shares the same data but allows for changes in shape or strides without altering the original data. Modifications to the data through np2 will affect np1, but changes to the shape of np2 will not affect np1.

`np2 = np1.copy()` creates a deepcopy of np1

### Reshaping

In [11]:
# 1D array
np1 = np.arange(1, 13) # 1,2,3,4,5,6,7,8,9,10,11,12
print(f"Original 1D array: \n {np1} \n")

print(f"shape is {np1.shape}")

Original 1D array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 

shape is (12,)


In [ ]:
# reshaping to 2D array
np2 = np1.reshape(3, 4)
print(f"Reshaped 2D array: \n {np2} \n")

# reshaping to 3D array
np3 = np1.reshape(2, 2, 3)
print(f"Reshaped 3D array: \n {np3}")

you can use `-1` to automatically reshape

In [17]:
np2 = np1.reshape(3, -1)
np3 = np1.reshape(-1, 3, 2)
# -1 means that the value is inferred from the length of the array and the remaining dimensions

np1 = np3.reshape(-1)
# this flattens np3 into a 1D array

### Iterating through ndarrays

you can iterate manually through nested loops:

In [ ]:
np1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
for row in np1:
    print(row)
    for element in row:
        print(element)

`np.nditer()` is more convenient to iterate through every element

In [ ]:
for x in np.nditer(np1):
    print(x)

`np.ndenumerate` acts like enumerate(). It returns a tuple with index and element at that index

In [ ]:
for (index, x) in np.ndenumerate(np1):
    print(index, x)