# NumPy Fundamentals

## Intro To Numpy

If you don't have NumPy installed, `pip install numpy`

In [1]:
import numpy as np

### Creating NumPy arrays

In [10]:
# convert python list to numpy array
np1 = np.array([1,2,3,4,5]) # 1,2,3,4,5

# np.arange(start, stop, step)
np2 = np.arange(5) # 0,1,2,3,4
np3 = np.arange(5, 10) # 5,6,7,8,9
np4 = np.arange(5, 10, 2) # 5,7,9

# np.linspace(start, stop, num)
np5 = np.linspace(0, 10, 5) # 0,2.5,5,7.5,10

# np.zero and np.ones
np6 = np.zeros(5) # 0,0,0,0,0
np7 = np.ones(5) # 1,1,1,1,1

# np.full(shape, value)
np8 = np.full(5, 5) # 5,5,5,5,5
np9 = np.full((2,2), 5) # [[5,5],[5,5]]

# np.eye
np10 = np.eye(5) # 5x5 identity matrix

# np.random.rand
np11 = np.random.rand(5) # 5 random numbers between 0 and 1

# np.random.randint
np12 = np.random.randint(1, 10, 5) # 5 random numbers between 1 and 10


**seeing the shape**

In [16]:
print(f"shape: {np9.shape}") # prints the shape of the array
print(np9)

shape: (2, 2)
[[5 5]
 [5 5]]


### Slicing and indexing

**SLICING**

In [ ]:
np1 = np.arange(1, 10) # 1,2,3,4,5,6,7,8,9

print(np1[1:5]) # 2,3,4,5
print(np1[:5]) # 1,2,3,4,5

print(np1[::2]) # 1,3,5,7,9
print(np1[::]) # 1,2,3,4,5,6,7,8,9
print(np1[::-1]) # 9,8,7,6,5,4,3,2,1
print(np1[1:-1:-1]) # empty array. If the step is negative, the start and stop should be reversed.

what if the array is not 1d?

In [ ]:
np2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np2[::-1])
print(np2[::-1, ::-1])
# we can observe that slicing needs to be specified for each dimension
# the first position is the 'outermost' dimension, and the last position is the 'innermost' dimension

**[EXTRA]** There are more advanced slicing/indexing techniques such as:  
- Integer array indexing  
- Fancy indexing  
- Ellipsis and np.newaxis  


**INDEXING**

generally, accessing in single-step `arr[x,y]` is more efficient than doing `arr[x][y]`

In [ ]:
np3 = np.array([[1,2,3], [4,5,6], [7,8,9]])


print(np3[1,2])
# This is a single-step operation where NumPy directly accesses the specified element using multidimensional indexing

print(np3[1][2]) # 6
# This is a two-step operation where NumPy first accesses the first dimension and then the second dimension

**[EXTRA] boolean indexing**

In [32]:

a = np.array([1, 2, 3, 4, 5])
# Create a boolean array where True represents values greater than 2
bool_idx = a > 2

print(bool_idx)
# Output: [False False  True  True  True]

# Use this boolean array to index the original array
print(a[bool_idx])
# Output: [3 4 5]

# Or directly
print(a[a > 2])
# Output: [3 4 5]

[False False  True  True  True]
[3 4 5]
[3 4 5]


### NumPy Universal Functions